/*
 * DBRowNavigator.java
 *
 * Created on January 5, 2002, 3:34 PM
 */

package ca.mb.armchair.DBAppBuilder.Widgets;

import ca.mb.armchair.DBAppBuilder.Beans.*;
import ca.mb.armchair.DBAppBuilder.Helpers.*;
import ca.mb.armchair.DBAppBuilder.Interfaces.*;

/**
 *
 * @author  creatist
 */
public class DBRowNavigator extends javax.swing.JPanel {

    /** Creates new panel for visual row navigation */
    public DBRowNavigator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelModify = new javax.swing.JPanel();
        dBRowButtonNew1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonNew();
        dBRowButtonUndo1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonUndo();
        dBRowButtonSave1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonSave();
        jPanelNavigate = new javax.swing.JPanel();
        dBRowButtonFirst1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonFirst();
        dBRowButtonPrevious1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonPrevious();
        jPanelRecord = new javax.swing.JPanel();
        dBRowRecordNumber1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowRecordNumber();
        dBRowButtonNext1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonNext();
        dBRowButtonLast1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonLast();
        jPanelDelete = new javax.swing.JPanel();
        dBRowButtonDelete1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonDelete();
        dBRowButtonDeleteSelected1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonDeleteSelected();

        setLayout(new java.awt.GridLayout(1, 0));

        setMinimumSize(new java.awt.Dimension(50, 20));
        setPreferredSize(new java.awt.Dimension(385, 20));
        jPanelModify.setLayout(new java.awt.GridLayout(1, 0));

        dBRowButtonNew1.setText("new");
        dBRowButtonNew1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelModify.add(dBRowButtonNew1);

        dBRowButtonUndo1.setText("undo");
        dBRowButtonUndo1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelModify.add(dBRowButtonUndo1);

        dBRowButtonSave1.setText("save");
        dBRowButtonSave1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelModify.add(dBRowButtonSave1);

        add(jPanelModify);

        jPanelNavigate.setLayout(new java.awt.GridLayout(1, 0));

        dBRowButtonFirst1.setText("<<");
        dBRowButtonFirst1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelNavigate.add(dBRowButtonFirst1);

        dBRowButtonPrevious1.setText("<");
        dBRowButtonPrevious1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelNavigate.add(dBRowButtonPrevious1);

        jPanelRecord.setLayout(new java.awt.GridLayout(1, 0));

        jPanelRecord.setBorder(new javax.swing.border.EtchedBorder(null, java.awt.Color.lightGray));
        jPanelRecord.setMinimumSize(new java.awt.Dimension(40, 21));
        jPanelRecord.setPreferredSize(new java.awt.Dimension(60, 21));
        jPanelRecord.add(dBRowRecordNumber1);

        jPanelNavigate.add(jPanelRecord);

        dBRowButtonNext1.setText(">");
        dBRowButtonNext1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelNavigate.add(dBRowButtonNext1);

        dBRowButtonLast1.setText(">>");
        dBRowButtonLast1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelNavigate.add(dBRowButtonLast1);

        add(jPanelNavigate);

        jPanelDelete.setLayout(new java.awt.GridLayout(1, 0));

        dBRowButtonDelete1.setText("delete");
        dBRowButtonDelete1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelDelete.add(dBRowButtonDelete1);

        dBRowButtonDeleteSelected1.setText("delete selected");
        dBRowButtonDeleteSelected1.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanelDelete.add(dBRowButtonDeleteSelected1);

        add(jPanelDelete);

    }//GEN-END:initComponents

    /** Set the DBRow to control */
    public void setDBRow(DBRow dbR) {
        dBRowButtonNew1.setDBRow(dbR);
        dBRowButtonUndo1.setDBRow(dbR);
        dBRowButtonSave1.setDBRow(dbR);
        dBRowButtonFirst1.setDBRow(dbR);
        dBRowButtonPrevious1.setDBRow(dbR);
        dBRowRecordNumber1.setDBRow(dbR);
        dBRowButtonNext1.setDBRow(dbR);
        dBRowButtonLast1.setDBRow(dbR);
        dBRowButtonDelete1.setDBRow(dbR);
        dBRowButtonDeleteSelected1.setDBRow(dbR);
    }
    
    /** Get the DBRow we're controlling */
    public DBRow getDBRow() {
        return dBRowButtonNew1.getDBRow();
    }
    
    /** Identify a DBRowSelector that will manage record deletion when there are multiple selections. */
    public void setDBRowSelector(DBRowSelector rs) {
        dBRowButtonDeleteSelected1.setDBRowSelector(rs);
    }
    
    /** Return the DBRowSelector that is managing record deletion.  Return null if there isn't one. */
    public DBRowSelector getDBRowSelector() {
        return dBRowButtonDeleteSelected1.getDBRowSelector();
    }
    
    /** Getter for property canInsert.
     * @return Value of property canInsert.
     */
    public boolean isInsertable() {
        return dBRowButtonNew1.isVisible();
    }
    
    /** Setter for property canInsert.
     * @param canInsert New value of property canInsert.
     */
    public void setInsertable(boolean canInsert) {
        dBRowButtonNew1.setVisible(canInsert);
        if (canInsert)
            setUpdateable(true);
    }
    
    /** Getter for property Updateable */
    public boolean isUpdateable() {
        return dBRowButtonUndo1.isVisible();
    }
    
    /** Setter for property Updateable */
    public void setUpdateable(boolean canUpdate) {
        dBRowButtonUndo1.setVisible(canUpdate);
        dBRowButtonSave1.setVisible(canUpdate);
    }
    
    /** Getter for property Navigable */
    public boolean isNavigable() {
        return dBRowButtonFirst1.isVisible();
    }
    
    /** Setter for property Navigable.
     * @param canFirst New value of property canFirst.
     */
    public void setNavigable(boolean canNavigate) {
        dBRowButtonFirst1.setVisible(canNavigate);
        dBRowButtonNext1.setVisible(canNavigate);
        dBRowButtonPrevious1.setVisible(canNavigate);
        dBRowButtonLast1.setVisible(canNavigate);
    }
    
    /** Getter for property canDelete.
     * @return Value of property canDelete.
     */
    public boolean isDeletable() {
        return dBRowButtonDelete1.isVisible();
    }
    
    /** Setter for property canDelete.
     * @param canDelete New value of property canDelete.
     */
    public void setDeletable(boolean canDelete) {
        dBRowButtonDelete1.setVisible(canDelete);
    }
    
    /** Getter for property canSelectRecordByNumber.
     * @return Value of property canSelectRecordByNumber.
     */
    public boolean isSelectableByRecordNumber() {
        return jPanelRecord.isVisible();
    }
    
    /** Setter for property canSelectRecordByNumber.
     * @param canSelectRecordByNumber New value of property canSelectRecordByNumber.
     */
    public void setSelectableByRecordNumber(boolean canSelectRecordByNumber) {
        jPanelRecord.setVisible(canSelectRecordByNumber);
        dBRowRecordNumber1.setVisible(canSelectRecordByNumber);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonUndo dBRowButtonUndo1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonDeleteSelected dBRowButtonDeleteSelected1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowRecordNumber dBRowRecordNumber1;
    private javax.swing.JPanel jPanelRecord;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonNew dBRowButtonNew1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonDelete dBRowButtonDelete1;
    private javax.swing.JPanel jPanelModify;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonNext dBRowButtonNext1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonFirst dBRowButtonFirst1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonLast dBRowButtonLast1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonPrevious dBRowButtonPrevious1;
    private javax.swing.JPanel jPanelNavigate;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowButtonSave dBRowButtonSave1;
    private javax.swing.JPanel jPanelDelete;
    // End of variables declaration//GEN-END:variables

}
