package ca.mb.armchair.DBAppBuilder.Demos;

/*
 * Test.java
 *
 * Created on January 13, 2002, 8:04 AM
 */

import ca.mb.armchair.DBAppBuilder.Widgets.*;
import ca.mb.armchair.DBAppBuilder.Beans.*;
import ca.mb.armchair.DBAppBuilder.Helpers.*;
import ca.mb.armchair.DBAppBuilder.Interfaces.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;

/**
 * Illustration of a simple custom form.
 *
 * This demo assumes the sample database -- dbappbuilder -- is installed.
 *
 * @author  creatist
 */
public class SimpleCustomForm extends javax.swing.JFrame {

    /** Creates new form Test */
    public SimpleCustomForm() {
        initComponents();
        
        dBRows.addColumn("DBCheckBox",dBCheckBox1);
        dBRows.addColumn("DBComboBox",dBComboBox1);
        dBRows.addColumn("DBLabel",dBLabel1);
        dBRows.addColumn("DBPasswordField",dBPasswordField1);
        dBRows.addColumn("DBRadioButton",dBRadioButton1);
        dBRows.addColumn("DBScrollBar",dBScrollBar1);
        dBRows.addColumn("DBSlider",dBSlider1);
        dBRows.addColumn("DBTextField",dBTextField1);
        dBRows.addColumn("DBToggleButton",dBToggleButton1);
        dBRows.addColumn("DBList",dBList1);
        dBRows.addColumn("DBTextArea",dBTextArea1);
        dBRows.addColumn("DBEditorPane",dBEditorPane1);
        dBRows.addColumn("DBTextPane",dBTextPane1);
        dBRows.addOID();
        dBRows.generateSQL();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        dBKey = new ca.mb.armchair.DBAppBuilder.Beans.DBColumnValues();
        dBRows = new ca.mb.armchair.DBAppBuilder.Beans.DBRow();
        jScrollPaneForm = new javax.swing.JScrollPane();
        jPanelForm = new javax.swing.JPanel();
        jPaneldBCheckBox1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dBCheckBox1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBCheckBox();
        jPaneldBComboBox1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dBComboBox1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBComboBox();
        jPaneldBLabel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dBLabel1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBLabel();
        jPaneldBPasswordField1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        dBPasswordField1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBPasswordField();
        jPaneldBRadioButton1 = new javax.swing.JPanel();
        jLabel311 = new javax.swing.JLabel();
        dBRadioButton1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBRadioButton();
        jPaneldBScrollBar1 = new javax.swing.JPanel();
        jLabel3111 = new javax.swing.JLabel();
        dBScrollBar1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBScrollBar();
        jPaneldBSlider1 = new javax.swing.JPanel();
        jLabel31111 = new javax.swing.JLabel();
        dBSlider1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBSlider();
        jPaneldBTextField1 = new javax.swing.JPanel();
        jLabel311111 = new javax.swing.JLabel();
        dBTextField1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBTextField();
        jPaneldBToggleButton1 = new javax.swing.JPanel();
        jLabel3111111 = new javax.swing.JLabel();
        dBToggleButton1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBToggleButton();
        jPaneldBList1 = new javax.swing.JPanel();
        jLabel31111111 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dBList1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBList();
        jPaneldBTextPane1 = new javax.swing.JPanel();
        jLabel31111111111 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dBTextPane1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBTextPane();
        jPaneldBEditorPane1 = new javax.swing.JPanel();
        jLabel3111111111 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dBEditorPane1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBEditorPane();
        jPaneldBTextArea1 = new javax.swing.JPanel();
        jLabel311111111 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dBTextArea1 = new ca.mb.armchair.DBAppBuilder.Widgets.DBTextArea();
        jScrollPaneController = new javax.swing.JScrollPane();
        jPanelController = new javax.swing.JPanel();
        dBRowNavigator = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowNavigator();
        jPanelLocator = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dBRowLocator = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowLocator();
        jPanel1 = new javax.swing.JPanel();
        dBRowSelector = new ca.mb.armchair.DBAppBuilder.Widgets.DBRowSelector();

        dBRows.setSQLOrder("testnumber");
        dBRows.setUpdateableViewName("test");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelForm.setMaximumSize(new java.awt.Dimension(1024, 768));
        jPanelForm.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelForm.setPreferredSize(new java.awt.Dimension(800, 600));
        jPaneldBCheckBox1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("DBCheckBox: ");
        jPaneldBCheckBox1.add(jLabel1);

        jPaneldBCheckBox1.add(dBCheckBox1);

        jPanelForm.add(jPaneldBCheckBox1);

        jPaneldBComboBox1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("DBComboBox: ");
        jPaneldBComboBox1.add(jLabel2);

        dBComboBox1.setSQL("select tablename from pg_tables");
        jPaneldBComboBox1.add(dBComboBox1);

        jPanelForm.add(jPaneldBComboBox1);

        jPaneldBLabel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("DBLabel:");
        jPaneldBLabel1.add(jLabel3);

        dBLabel1.setText("dBLabel1");
        jPaneldBLabel1.add(dBLabel1);

        jPanelForm.add(jPaneldBLabel1);

        jPaneldBPasswordField1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel31.setText("DBPasswordField:");
        jPaneldBPasswordField1.add(jLabel31);

        dBPasswordField1.setPreferredSize(new java.awt.Dimension(100, 13));
        jPaneldBPasswordField1.add(dBPasswordField1);

        jPanelForm.add(jPaneldBPasswordField1);

        jPaneldBRadioButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel311.setText("DBRadioButton:");
        jPaneldBRadioButton1.add(jLabel311);

        jPaneldBRadioButton1.add(dBRadioButton1);

        jPanelForm.add(jPaneldBRadioButton1);

        jPaneldBScrollBar1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3111.setText("DBScrollBar:");
        jPaneldBScrollBar1.add(jLabel3111);

        dBScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        dBScrollBar1.setMinimumSize(new java.awt.Dimension(50, 17));
        dBScrollBar1.setPreferredSize(new java.awt.Dimension(200, 17));
        jPaneldBScrollBar1.add(dBScrollBar1);

        jPanelForm.add(jPaneldBScrollBar1);

        jPaneldBSlider1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel31111.setText("DBSlider:");
        jPaneldBSlider1.add(jLabel31111);

        jPaneldBSlider1.add(dBSlider1);

        jPanelForm.add(jPaneldBSlider1);

        jPaneldBTextField1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel311111.setText("DBTextField:");
        jPaneldBTextField1.add(jLabel311111);

        dBTextField1.setText("dBTextField1");
        dBTextField1.setMinimumSize(new java.awt.Dimension(50, 17));
        dBTextField1.setPreferredSize(new java.awt.Dimension(200, 17));
        jPaneldBTextField1.add(dBTextField1);

        jPanelForm.add(jPaneldBTextField1);

        jPaneldBToggleButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3111111.setText("DBToggleButton:");
        jPaneldBToggleButton1.add(jLabel3111111);

        dBToggleButton1.setText("dBToggleButton1");
        jPaneldBToggleButton1.add(dBToggleButton1);

        jPanelForm.add(jPaneldBToggleButton1);

        jPaneldBList1.setLayout(new java.awt.BorderLayout());

        jLabel31111111.setText("DBList:");
        jPaneldBList1.add(jLabel31111111, java.awt.BorderLayout.NORTH);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 100));
        dBList1.setSQL("select tablename, hasindexes from pg_tables");
        jScrollPane1.setViewportView(dBList1);

        jPaneldBList1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelForm.add(jPaneldBList1);

        jPaneldBTextPane1.setLayout(new java.awt.BorderLayout());

        jLabel31111111111.setText("DBTextPane:");
        jPaneldBTextPane1.add(jLabel31111111111, java.awt.BorderLayout.NORTH);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(250, 200));
        dBTextPane1.setPreferredSize(new java.awt.Dimension(6, 6));
        jScrollPane4.setViewportView(dBTextPane1);

        jPaneldBTextPane1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanelForm.add(jPaneldBTextPane1);

        jPaneldBEditorPane1.setLayout(new java.awt.BorderLayout());

        jLabel3111111111.setText("DBEditorPane:");
        jPaneldBEditorPane1.add(jLabel3111111111, java.awt.BorderLayout.NORTH);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(250, 200));
        jScrollPane3.setViewportView(dBEditorPane1);

        jPaneldBEditorPane1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanelForm.add(jPaneldBEditorPane1);

        jPaneldBTextArea1.setLayout(new java.awt.BorderLayout());

        jLabel311111111.setText("DBTextArea:");
        jPaneldBTextArea1.add(jLabel311111111, java.awt.BorderLayout.NORTH);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 200));
        dBTextArea1.setPreferredSize(new java.awt.Dimension(200, 13));
        jScrollPane2.setViewportView(dBTextArea1);

        jPaneldBTextArea1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanelForm.add(jPaneldBTextArea1);

        jScrollPaneForm.setViewportView(jPanelForm);

        getContentPane().add(jScrollPaneForm, java.awt.BorderLayout.CENTER);

        jPanelController.setLayout(new java.awt.BorderLayout());

        dBRowNavigator.setDBRow(dBRows);
        dBRowNavigator.setDBRowSelector(dBRowSelector);
        jPanelController.add(dBRowNavigator, java.awt.BorderLayout.NORTH);

        jPanelLocator.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Select record by OID: ");
        jPanelLocator.add(jLabel4, java.awt.BorderLayout.WEST);

        dBRowLocator.setDBRow(dBRows);
        dBRowLocator.setSQL("select testnumber from test order by testnumber");
        dBRowLocator.setColumnName("testnumber");
        dBRowLocator.setMinimumSize(new java.awt.Dimension(52, 13));
        dBRowLocator.setPreferredSize(new java.awt.Dimension(52, 13));
        jPanelLocator.add(dBRowLocator, java.awt.BorderLayout.CENTER);

        jPanelController.add(jPanelLocator, java.awt.BorderLayout.CENTER);

        jScrollPaneController.setViewportView(jPanelController);

        getContentPane().add(jScrollPaneController, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(20, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 10));
        dBRowSelector.setBorder(null);
        dBRowSelector.setDBRow(dBRows);
        dBRowSelector.setFont(new java.awt.Font("Dialog", 0, 10));
        dBRowSelector.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(dBRowSelector, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dBRows.update();
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new SimpleCustomForm().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelLocator;
    private javax.swing.JPanel jPaneldBRadioButton1;
    private javax.swing.JPanel jPanelController;
    private javax.swing.JPanel jPaneldBLabel1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBPasswordField dBPasswordField1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBScrollBar dBScrollBar1;
    private javax.swing.JLabel jLabel3111111;
    private javax.swing.JLabel jLabel31111111;
    private javax.swing.JPanel jPaneldBTextPane1;
    private javax.swing.JPanel jPaneldBTextArea1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBTextPane dBTextPane1;
    private javax.swing.JScrollPane jScrollPaneController;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowLocator dBRowLocator;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBTextArea dBTextArea1;
    private ca.mb.armchair.DBAppBuilder.Beans.DBRow dBRows;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel311111111;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel311111;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneForm;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRadioButton dBRadioButton1;
    private javax.swing.JPanel jPaneldBComboBox1;
    private javax.swing.JPanel jPaneldBTextField1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBLabel dBLabel1;
    private javax.swing.JPanel jPaneldBSlider1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPaneldBCheckBox1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBComboBox dBComboBox1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBSlider dBSlider1;
    private javax.swing.JScrollPane jScrollPane1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBCheckBox dBCheckBox1;
    private javax.swing.JPanel jPaneldBPasswordField1;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel31111111111;
    private javax.swing.JLabel jLabel3111;
    private javax.swing.JPanel jPaneldBEditorPane1;
    private javax.swing.JPanel jPaneldBScrollBar1;
    private ca.mb.armchair.DBAppBuilder.Beans.DBColumnValues dBKey;
    private javax.swing.JPanel jPanelForm;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBEditorPane dBEditorPane1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowSelector dBRowSelector;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBRowNavigator dBRowNavigator;
    private javax.swing.JPanel jPaneldBList1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBList dBList1;
    private javax.swing.JPanel jPaneldBToggleButton1;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBToggleButton dBToggleButton1;
    private javax.swing.JLabel jLabel31111;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel3111111111;
    private ca.mb.armchair.DBAppBuilder.Widgets.DBTextField dBTextField1;
    // End of variables declaration//GEN-END:variables

}
