package ca.mb.armchair.DBAppBuilder.Beans;

/*
 * DialogLongString.java
 *
 * Created on December 23, 2001, 5:37 PM
 */

/**
 *
 * @author  creatist
 */
public class DialogLongString extends javax.swing.JDialog {

    /** Creates new form DialogLongString */
    public DialogLongString() {
        initComponents();
    }
    
    /** Creates new form DialogLongString, given message */
    public DialogLongString(String Msg) {
        initComponents();
        setMessage(Msg);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jMessage = new javax.swing.JTextPane();
        jButtonOk = new javax.swing.JButton();

        setTitle("Message");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPaneMessage.setPreferredSize(new java.awt.Dimension(600, 300));
        jMessage.setPreferredSize(new java.awt.Dimension(6, 6));
        jScrollPaneMessage.setViewportView(jMessage);

        getContentPane().add(jScrollPaneMessage, java.awt.BorderLayout.CENTER);

        jButtonOk.setText("Close");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doOk(evt);
            }
        });

        getContentPane().add(jButtonOk, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    /** Set the message to display */
    public void setMessage(String m) {
        jMessage.setText(m);
        jScrollPaneMessage.getVerticalScrollBar().setValue(0);
    }
    
    private void doOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doOk
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_doOk

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JTextPane jMessage;
    private javax.swing.JButton jButtonOk;
    // End of variables declaration//GEN-END:variables

}
