package ca.mb.armchair.DBAppBuilder.Beans;

/*
 * DialogSelectDB.java
 *
 * Created on November 14, 2001, 11:46 AM
 */

import java.sql.*;

/**
 *
 * @author  creatist
 */
public class DialogDBSelect extends javax.swing.JDialog {
    
    /** Creates new empty form DialogSelectDB */
    public DialogDBSelect() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        fldName.setText(db.getDescription());
        fldDBDriver.setText(db.getDriver());
        fldDBURL.setText(db.getURL());
        fldLogin.setText(db.getLogin());
        fldPassword.setText(db.getPassword());
        jCheckBoxLogging.getModel().setSelected(db.isLogging());
    }
    
    /** Creates new form DialogSelectDB from existing databaseConnection */
    public DialogDBSelect(DatabaseConnection db) {
        initComponents();
        fldName.setText(db.getDescription());
        fldDBDriver.setText(db.getDriver());
        fldDBURL.setText(db.getURL());
        fldLogin.setText(db.getLogin());
        fldPassword.setText(db.getPassword());
        jCheckBoxLogging.getModel().setSelected(db.isLogging());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        fldDBDriver = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldDBURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fldLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxLogging = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fldStatus = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Select Database");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Database driver:");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel1, gridBagConstraints);

        fldName.setToolTipText("A name that uniquely identifies this connection.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(fldName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(fldDBDriver, gridBagConstraints);

        jLabel2.setText("Database URL:");
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(fldDBURL, gridBagConstraints);

        jLabel3.setText("Login:");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(fldLogin, gridBagConstraints);

        jLabel4.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(fldPassword, gridBagConstraints);

        jLabel7.setText("Enable logging:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jCheckBoxLogging, gridBagConstraints);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 4, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(btnOk, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 4, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(btnCancel, gridBagConstraints);

        jLabel5.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Connection name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel6, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 50));
        fldStatus.setWrapStyleWord(true);
        fldStatus.setEnabled(false);
        jScrollPane1.setViewportView(fldStatus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
       
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dbC=null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dbC = new DatabaseConnection(
            fldName.getText(),
            fldDBDriver.getText(),
            fldLogin.getText(),
            fldPassword.getPassword().toString(),
            fldDBURL.getText());
        dbC.setLogging(jCheckBoxLogging.isSelected());
        Connection con=dbC.getConnection();
        if (con==null)
            fldStatus.setText("1 Connection failed:\n\n"+dbC.getStatus());
        else {
            fldStatus.setText("0 Connection succeeded:\n\n"+dbC.getStatus());
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed
    
    /** Obtain a connection.  Null if no connection obtained. */
    public DatabaseConnection getDatabaseConnection() {
        return dbC;
    }
        
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private DatabaseConnection dbC = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fldDBDriver;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField fldLogin;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField fldDBURL;
    private javax.swing.JCheckBox jCheckBoxLogging;
    private javax.swing.JTextArea fldStatus;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField fldName;
    // End of variables declaration//GEN-END:variables
    
}
